#!/bin/sh
set -xe
apt-get update -y
DEB_HOST_ARCH=$(dpkg --print-architecture)
zfsver=$(apt-cache show zfs-dkms | grep Version: | head -n1 | sed -e 's@Version: \(.*\)-.*@\1@')

if ! (echo "amd64 arm64 ppc64el s390x" | grep -o $DEB_HOST_ARCH); then
	exit 0
fi

apt-get install spl-dkms -y
apt-get install zfs-dkms -y

for kver in $(ls /lib/modules); do
dkms build spl/$zfsver -k $kver
dkms build zfs/$zfsver -k $kver
done
