#!/bin/bash

set -e

# extracted from https://github.com/openzfs/zfs/blob/master/.github/workflows/scripts/setup-functional.sh (part3)
tests=(
  nestedfs
  nopwrite
  no_space
  online_offline
  pam
  pool_checkpoint
  pool_names
  poolversion
  privilege
  procfs
  projectquota
  pyzfs
  quota
  scrub_mirror
  simd
  slog
  snapshot
  snapused
  sparse
  stat
  suid
  tmpfile
  trim
  truncate
  upgrade
  user_namespace
  userquota
  vdev_zaps
  write_dirs
  xattr
  zpool_influxdb
  zvol
)

test_list="$(IFS=,; echo "${tests[*]}")"

./debian/tests/zfs-test-suite "$test_list"
